---
# tasks file for grafana
- name: Add grafana apt key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: "package.list"
  when: ansible_distribution == 'Ubuntu'

- name: Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Add grafana rpm key
  rpm_key:
    key: https://packages.grafana.com/gpg.key
    state: present
  when: ansible_distribution == 'CentOS'

- name: Add grafana repository
  yum_repository:
    name: grafana
    description: Adds the repository of grafana
    baseurl: https://packages.grafana.com/oss/rpm
    gpgcheck: True
    gpgkey: https://packages.grafana.com/gpg.key
  when: ansible_distribution == 'CentOS'

- name: Install grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes
  when: ansible_distribution == 'CentOS'
