---
# tasks file for nagioscentos
- name: Install packages for nagios
  yum:
    name:
      - gcc
      - glibc
      - glibc-common
      - perl
      - httpd
      - php
      - wget
      - gd
      - gd-devel
    state: latest
    update_cache: yes

- name: Stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Download and unarchive nagios core
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create make file
  shell: cd /tmp/nagioscore-nagios-4.4.5; sh /tmp/nagioscore-nagios-4.4.5/configure
  register: make_file
    # cwhen: nagios_source.changed

- name: Compile from source
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: all
  become: yes
    # when: make_file.changed

- name: Create user and group
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-groups-users
  become: yes
    # when: make_file.changed

- name: Add apache to nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: Install binaries
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install
  become: yes
    # when: make_file.changed

- name: Install service
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-daemoninit
  become: yes
    # when: make_file.changed
  register: daemoninit

- name: Enable httpd
  service:
    name: httpd
    enabled: yes
      # when: daemoninit.changed

- name: Install command mode
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-commandmode
  become: yes
    # when: make_file.changed

- name: Install configuration files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-config
  become: yes
    # when: make_file.changed

- name: Install apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-webconf
  become: yes
    # when: make_file.changed
  register: install_webconf

- name: Copy nagios service unit
  copy:
    content: |
      [Unit]
      Description=Nagios
      BindTo=network.target
      [Install]
      WantedBy=multi-user.target
      [Service]
      User=nagios
      Group=nagios
      Type=simple
      ExecStart=/usr/local/nagios/bin/nagios /usr/local/nagios/etc/nagios.cfg
    dest: "/etc/systemd/system/nagios.service"

- name: Start and enable apache
  service:
    name: httpd
    state: started
    enabled: yes
      # when: install_webconf.changed

- name: Start and enable nagios
  service:
    name: nagios
    state: started
    enabled: yes
